### ISSUE TITLE
Unable to install the add-on on Statamic 2.8.7

### ISSUE THREAD

**Issue by chroi** [edalzell/iCal#2]
I've git cloned the adding in "addons", so I have a "iCal" directory in the "addons" directory.

Here's what happens next :

`➜  git git:(master) ✗ php please addons:refresh
[✗] This command is deprecated. Please use php please update:addons

Adding packages: erin-dalzell/ical, marbles/sitemap
Please wait while dependencies are updated via Composer. This may take a while.
The command "php composer.phar update erin-dalzell/ical marbles/sitemap --prefer-dist --no-dev --optimize-autoloader" failed.
Exit Code: 2(Misuse of shell builtins)

Output:
================

Error Output:
================
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package erin-dalzell/ical could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.

Dependencies updated!
`

same if I do `php please update:addons`

Unfortunately, I don't understand addons well enough to understand what's going on.

**Comment by edalzell** [comment]
I could not reproduce, can you please try it with a new installation of Statamic?

**Comment by chroi** [comment]
Same happens on a fresh 2.8.8 install. I'm running macOS. Can this be an issue of filename case sentitivity?

**Comment by chroi** [comment]
Ok I'm sorry... My mistake : 

I was cloning the whole repo in addons and didn't see that there was two level of directories. It's working now.
